namespace:
  create: true
  labels:
    istio.io/dataplane-mode: ambient

image:
  pullPolicy: Always
  tag: sha-ca490bf

gateway:
  enabled: true
  createGateway: false
  className: istio
  host: voting.arguswatcher.net
  parentRef:
    name: istio-ingress
    namespace: istio-ingress

postgres:
  persistence:
    size: 2Gi

metrics:
  enabled: false

tests:
  smoke:
    enabled: true
  smokeExternal:
    enabled: true
    host: voting.arguswatcher.net
  load:
    enabled: true
    targetUrl: https://voting.arguswatcher.net
