image:
  repository: simonangelfong/voting-api
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8000

gateway:
  enabled: false
  createGateway: true
  className: nginx
  host: voting.local
  parentRef:
    name: ""
    namespace: ""
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
  auth:
    username: voting
    password: voting
    database: voting
    existingSecret: ""
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

flyway:
  enabled: true
  image:
    repository: flyway/flyway
    tag: "10-alpine"
  connectRetries: 30
  baselineOnMigrate: true
  baselineVersion: "1"

api:
  env: []

metrics:
  enabled: true
  path: /metrics
  interval: 30s
