apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: To-do demo app
  sourceRepos:
    - https://github.com/simonangel-fong/project-eks-argocd
  destinations:
    - server: https://kubernetes.default.svc
      namespace: todo
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
