apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: team-a
  labels:
    team: team-a
    app: web
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: http
