apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway-api-crds
  namespace: argocd
  labels:
    scope: platform
    capability: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-16"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.6.0
    path: config/crd/standard
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
