apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: multi-tenant-eks-dev/slack-webhook
        property: url
