# Node config for the database workload class.
# Slightly larger root volume than general to accommodate stateful
# workloads' scratch space and container image cache.
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: database
spec:
  role: multi-tenant-eks-dev-karpenter-node
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: multi-tenant-eks-dev
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: multi-tenant-eks-dev
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 100Gi
        deleteOnTermination: true
        encrypted: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  tags:
    karpenter.sh/discovery: multi-tenant-eks-dev
    workload-class: database
