{{- if .Values.web.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-web
  labels:
    {{- include "todo.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  strategy:
    canary:
      canaryService: todo-web-canary
      stableService: todo-web
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute:
              name: todo-web
              namespace: {{ .Release.Namespace }}
      steps:
        {{- toYaml .Values.web.canary.steps | nindent 8 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "todo.commonLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.web.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.global.image.repository }}:{{ .Values.web.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
