# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: platform-security
#   namespace: argocd
#   labels:
#     scope: platform
#     capability: security
#   annotations:
#     argocd.argoproj.io/sync-wave: "-20"
#   finalizers:
#     - argocd.argoproj.io/resources-finalizer
# spec:
#   project: platform
#   source:
#     repoURL: https://github.com/simonangel-fong/project-eks-argocd
#     targetRevision: master
#     path: argocd/platform-capabilities/security
#     directory:
#       recurse: false
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - ApplyOutOfSyncOnly=true
