apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: todo
  source:
    repoURL: https://github.com/simonangel-fong/project-eks-argocd
    targetRevision: master
    path: demo-app/to-do-app/chart
    helm:
      releaseName: todo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
    - group: networking.istio.io
      kind: VirtualService
      jsonPointers:
        - /spec/http
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
