apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: team-b
  labels:
    team: team-b
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: pg
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: team-b
  labels:
    team: team-b
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        team: team-b
        app: postgres
    spec:
      nodeSelector:
        workload-class: database
      tolerations:
        - key: workload-class
          value: database
          effect: NoSchedule
      containers:
        - name: postgres
          image: docker.io/postgres:16
          ports:
            - containerPort: 5432
              name: pg
          env:
            - name: POSTGRES_DB
              value: todo
            - name: POSTGRES_USER
              value: todo
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            exec:
              command: [pg_isready, -U, todo, -d, todo]
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command: [pg_isready, -U, todo, -d, todo]
            initialDelaySeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: gp3-iops
        resources:
          requests:
            storage: 20Gi
