apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-albc
  namespace: argocd
  labels:
    scope: platform
    capability: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 3.4.1 
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: multi-tenant-eks-dev
        region: ca-central-1
        vpcId: 
          vpc-09828470329db3b27
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
        replicaCount: 1
        tolerations:
          - key: workload-class
            operator: Equal
            value: platform
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
