apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kyverno-policies
  namespace: argocd
  labels:
    scope: platform
    capability: security
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://github.com/simonangel-fong/project-eks-argocd
    targetRevision: master
    path: argocd/platform-capabilities/security/kyverno-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[].skipBackgroundRequests
        - .spec.rules[].validate.allowExistingViolations
        - .spec.background
        - .spec.admission
        - .spec.emitWarning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
