apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster add-ons (ESO, ALBC, Karpenter)
  sourceRepos:
    - https://github.com/simonangel-fong/project-eks-argocd
    - https://aws.github.io/eks-charts
    - public.ecr.aws/karpenter
    - https://charts.external-secrets.io
    - https://istio-release.storage.googleapis.com/charts
    - https://github.com/kubernetes-sigs/gateway-api
    - https://prometheus-community.github.io/helm-charts
    - https://charts.jetstack.io
    - https://kubernetes-sigs.github.io/external-dns
    - https://kyverno.github.io/kyverno/
    - https://grafana.github.io/helm-charts
    - https://argoproj.github.io/argo-helm
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
