apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: team-b workload
  sourceRepos:
    - https://github.com/simonangel-fong/project-eks-argocd
  destinations:
    - server: https://kubernetes.default.svc
      namespace: team-b
  clusterResourceWhitelist:
    - group: gateway.networking.k8s.io
      kind: '*'
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
