apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster add-ons (ESO, ALBC, Karpenter)
  sourceRepos:
    - https://github.com/simonangel-fong/project-eks-argocd
    - https://aws.github.io/eks-charts
    - public.ecr.aws/karpenter
    - https://charts.external-secrets.io
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
