apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 04-karpenter-nodes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://github.com/simonangel-fong/project-eks-argocd
    targetRevision: master
    path: argocd/karpenter-nodes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
