apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 06-gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-16"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.5.1
    path: config/crd/experimental
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
