apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 07-istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-14"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.30.0
    helm:
      releaseName: istiod
      values: |
        profile: ambient
        env:
          ENABLE_CLUSTER_TRUST_BUNDLE_API: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
