apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 10-istio-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.30.2
    helm:
      releaseName: istio-ingress
      values: |
        service:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
