# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-operator-crds
#   namespace: argocd
#   finalizers:
#     - argocd.argoproj.io/resources-finalizer
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     chart: prometheus-operator-crds
#     targetRevision: 22.0.2
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
