crds:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
grafana:
  adminPassword: admin
  persistence:
    enabled: true
    storageClassName: gp3
    size: 5Gi
  defaultDashboardsEnabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: community
          orgId: 1
          folder: Community
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/community
  dashboards:
    community:
      node-exporter:
        gnetId: 1860
        revision: 37
        datasource: Prometheus
alertmanager:
  enabled: false
