apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-rollouts-notification-secret
  namespace: argo-rollouts
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: argo-rollouts-notification-secret
    creationPolicy: Owner
  data:
    - secretKey: slack-token
      remoteRef:
        key: multi-tenant-eks-dev/slack-webhook
        property: url
