apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: hello
    creationPolicy: Owner
  data:
    - secretKey: hello
      remoteRef:
        key: eks-argocd/test/hello
        property: hello
